# Colors (Gruvbox Material Medium Light)

# Default colors
[colors.primary]
background = '#fbf1c7'
foreground = '#654735'

# Normal colors
[colors.normal]
black   = '#654735'
red     = '#c14a4a'
green   = '#6c782e'
yellow  = '#b47109'
blue    = '#45707a'
magenta = '#945e80'
cyan    = '#4c7a5d'
white   = '#eee0b7'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#654735'
red     = '#c14a4a'
green   = '#6c782e'
yellow  = '#b47109'
blue    = '#45707a'
magenta = '#945e80'
cyan    = '#4c7a5d'
white   = '#eee0b7'

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 10  # Adjust the font size as needed
